################################################################################
# configuration
#
# override by adding your own parameters into your config.toml
################################################################################
[module.hugoVersion]
extended = true
min = "0.56.0"

[[module.mounts]]
source = "assets/js/youtube.js"
target = "assets/js/youtube.js"

[[module.mounts]]
source = "content/dnb-hugo-shortcodes"
target = "content/dnb-hugo-shortcodes"

[[module.mounts]]
source = "data/dnb/shortcodes"
target = "data/dnb/shortcodes"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "static"
target = "static"
