[module]

[module.hugoVersion]
extended = true
min = "0.56.0"
max = "0.83.1"

[[module.imports]]
path = "github.com/dnb-hugo/shortcodes/collection"
disabled = false
ignoreConfig = false
ignoreImports = false

#[[module.imports]]
#path = "github.com/dnb-hugo/shortcodes/pictures"
#disabled = false
#ignoreConfig = false
#ignoreImports = false

[[module.imports]]
path = "github.com/dnb-hugo/shortcodes/youtube"
disabled = false
ignoreConfig = false
ignoreImports = false
