[module.hugoVersion]
extended = true
min = "0.56.0"

[[module.mounts]]
source = "assets/libs/lite-vimeo/lite-vimeo.js"
target = "assets/libs/lite-vimeo/lite-vimeo.js"

[[module.mounts]]
source = "data"
target = "data"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "static"
target = "static"

# see https://github.com/paulirish/lite-youtube-embed for details
[[module.imports]]
path = "github.com/paulirish/lite-youtube-embed"
disabled = false
[[module.imports.mounts]]
source = "src/lite-yt-embed.css"
target = "assets/libs/liteyoutube/lite-yt-embed.scss"
[[module.imports.mounts]]
source = "src/lite-yt-embed.js"
target = "assets/libs/liteyoutube/lite-yt-embed.js"
