pygmentsUseClasses=true

[module.hugoVersion]
extended = true
min = "0.83.1"

[[module.mounts]]
source = "data"
target = "data"

[[module.mounts]]
source = "layouts"
target = "layouts"

# see https://github.com/paulirish/lite-youtube-embed for details
[[module.imports]]
path = "github.com/paulirish/lite-youtube-embed"
disabled = false

[[module.imports.mounts]]
source = "src/lite-yt-embed.css"
target = "assets/libs/liteyoutube/lite-yt-embed.scss"

[[module.imports.mounts]]
source = "src/lite-yt-embed.css"
target = "static/libs/liteyoutube/lite-yt-embed.css"

[[module.imports.mounts]]
source = "src/lite-yt-embed.js"
target = "assets/libs/liteyoutube/lite-yt-embed.js"

[[module.imports.mounts]]
source = "src/lite-yt-embed.js"
target = "static/libs/liteyoutube/lite-yt-embed.js"
